name: mediaverse
services:
  
  backend:
    restart: always
    image: mediaverse.azurecr.io/mediaverse_be
    ports:
      - 80:80
    depends_on:
      - database
    environment:
      - ConnectionStrings:DefaultConnection=User ID=postgres;Password=WeakPassword;Host=database;Port=5432;Database=postgres
      - CORS:http=https://mediaverse-fzgmcvh4h5h2ddhk.westeurope-01.azurewebsites.net
      - JWT:Audience=https://mediaverse-fzgmcvh4h5h2ddhk.westeurope-01.azurewebsites.net
      - ASPNETCORE_ENVIRONMENT=Development
  
  frontend:
    restart: always
    image: mediaverse.azurecr.io/mediaverse_fe
    ports:
      - 8080:8080
  

