name: mediaverse
services:
  
  backend:
    restart: always
    build:
      context: backend/MediaVerse
      dockerfile: MediaVerse.Client.Api/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - database
    environment:
      - ConnectionStrings:DefaultConnection=User ID=postgres;Password=WeakPassword;Host=database;Port=5432;Database=postgres
      - ASPNETCORE_ENVIRONMENT=Development
  
  frontend:
    restart: always
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
  
  database:
    restart: always
    image: postgres
    environment:
      - POSTGRES_PASSWORD=WeakPassword
    volumes:
      - mediaverse-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/data
    ports:
      - 5432:5432

volumes:
  mediaverse-data:
