name: mediaverse
services:
  
  backend:
    restart: always
    image: mediaverse.azurecr.io/mediaverse_be:a30aa91f10d22d410dcb1b136929b0afdf2fee23
    ports:
      - 8080:8080
    depends_on:
      - database
    environment:
      - ConnectionStrings:DefaultConnection=User ID=postgres;Password=WeakPassword;Host=database;Port=5432;Database=postgres
      - ASPNETCORE_ENVIRONMENT=Development
  
  frontend:
    restart: always
    image: mediaverse.azurecr.io/mediaverse_fe:a30aa91f10d22d410dcb1b136929b0afdf2fee23
    ports:
      - 3000:3000
  

