name: mediaverse
services:
  
  backend:
    restart: always
    image: mediaverse.azurecr.io/mediaverse_be
    ports:
      - 8081:8081
    depends_on:
      - database
    environment:
      - ConnectionStrings:DefaultConnection=User ID=postgres;Password=WeakPassword;Host=database;Port=5432;Database=postgres
      - ASPNETCORE_ENVIRONMENT=Development
  
  frontend:
    restart: always
    image: mediaverse.azurecr.io/mediaverse_fe
    ports:
      - 8080:8080
  

