name: mediaverse
services:
  
  backend:
    restart: always
    image: mediaverse.azurecr.io/mediaverse_be:6d95f57ec47d32a9a5a61291043170c627efb4b5
    ports:
      - 8080:8080
    depends_on:
      - database
    environment:
      - ConnectionStrings:DefaultConnection=User ID=postgres;Password=WeakPassword;Host=database;Port=5432;Database=postgres
      - ASPNETCORE_ENVIRONMENT=Development
  
  frontend:
    restart: always
    image: mediaverse.azurecr.io/mediaverse_fe:6d95f57ec47d32a9a5a61291043170c627efb4b5
    ports:
      - 3000:3000
  
  database:
    restart: always
    image: postgres
    environment:
      - POSTGRES_PASSWORD=WeakPassword
    volumes:
      - mediaverse-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/data
    ports:
      - 5432:5432

volumes:
  mediaverse-data:
