/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SearchIndexImport } from './routes/search/index'
import { Route as UsersSearchImport } from './routes/users/search'
import { Route as UsersIdImport } from './routes/users/$id'
import { Route as EntriesIdImport } from './routes/entries/$id'
import { Route as AuthorsIdImport } from './routes/authors/$id'
import { Route as ArticlesSearchImport } from './routes/articles/search'
import { Route as ArticlesCreateImport } from './routes/articles/create'
import { Route as ArticlesIdImport } from './routes/articles/$id'
import { Route as AmaSessionsIdImport } from './routes/ama-sessions/$id'
import { Route as AuthorsCreateIndexImport } from './routes/authors/create/index'
import { Route as UsersEditIdImport } from './routes/users/edit/$id'
import { Route as EntriesCreateReviewIdImport } from './routes/entries/create-review/$id'
import { Route as AuthorsEditIdImport } from './routes/authors/edit/$id'
import { Route as ArticlesEditIdImport } from './routes/articles/edit/$id'
import { Route as EntriesMoviesCreateIndexImport } from './routes/entries/movies/create/index'
import { Route as EntriesBooksCreateIndexImport } from './routes/entries/books/create/index'
import { Route as ReviewsUserIdEntriesEntryIdImport } from './routes/reviews/$userId/entries/$entryId'
import { Route as EntriesMoviesEditIdImport } from './routes/entries/movies/edit/$id'
import { Route as EntriesBooksEditIdImport } from './routes/entries/books/edit/$id'
import { Route as ReviewsUserIdEntriesEditEntryIdImport } from './routes/reviews/$userId/entries/edit/$entryId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const SearchIndexRoute = SearchIndexImport.update({
  path: '/search/',
  getParentRoute: () => rootRoute,
} as any)

const UsersSearchRoute = UsersSearchImport.update({
  path: '/users/search',
  getParentRoute: () => rootRoute,
} as any)

const UsersIdRoute = UsersIdImport.update({
  path: '/users/$id',
  getParentRoute: () => rootRoute,
} as any)

const EntriesIdRoute = EntriesIdImport.update({
  path: '/entries/$id',
  getParentRoute: () => rootRoute,
} as any)

const AuthorsIdRoute = AuthorsIdImport.update({
  path: '/authors/$id',
  getParentRoute: () => rootRoute,
} as any)

const ArticlesSearchRoute = ArticlesSearchImport.update({
  path: '/articles/search',
  getParentRoute: () => rootRoute,
} as any)

const ArticlesCreateRoute = ArticlesCreateImport.update({
  path: '/articles/create',
  getParentRoute: () => rootRoute,
} as any)

const ArticlesIdRoute = ArticlesIdImport.update({
  path: '/articles/$id',
  getParentRoute: () => rootRoute,
} as any)

const AmaSessionsIdRoute = AmaSessionsIdImport.update({
  path: '/ama-sessions/$id',
  getParentRoute: () => rootRoute,
} as any)

const AuthorsCreateIndexRoute = AuthorsCreateIndexImport.update({
  path: '/authors/create/',
  getParentRoute: () => rootRoute,
} as any)

const UsersEditIdRoute = UsersEditIdImport.update({
  path: '/users/edit/$id',
  getParentRoute: () => rootRoute,
} as any)

const EntriesCreateReviewIdRoute = EntriesCreateReviewIdImport.update({
  path: '/entries/create-review/$id',
  getParentRoute: () => rootRoute,
} as any)

const AuthorsEditIdRoute = AuthorsEditIdImport.update({
  path: '/authors/edit/$id',
  getParentRoute: () => rootRoute,
} as any)

const ArticlesEditIdRoute = ArticlesEditIdImport.update({
  path: '/articles/edit/$id',
  getParentRoute: () => rootRoute,
} as any)

const EntriesMoviesCreateIndexRoute = EntriesMoviesCreateIndexImport.update({
  path: '/entries/movies/create/',
  getParentRoute: () => rootRoute,
} as any)

const EntriesBooksCreateIndexRoute = EntriesBooksCreateIndexImport.update({
  path: '/entries/books/create/',
  getParentRoute: () => rootRoute,
} as any)

const ReviewsUserIdEntriesEntryIdRoute =
  ReviewsUserIdEntriesEntryIdImport.update({
    path: '/reviews/$userId/entries/$entryId',
    getParentRoute: () => rootRoute,
  } as any)

const EntriesMoviesEditIdRoute = EntriesMoviesEditIdImport.update({
  path: '/entries/movies/edit/$id',
  getParentRoute: () => rootRoute,
} as any)

const EntriesBooksEditIdRoute = EntriesBooksEditIdImport.update({
  path: '/entries/books/edit/$id',
  getParentRoute: () => rootRoute,
} as any)

const ReviewsUserIdEntriesEditEntryIdRoute =
  ReviewsUserIdEntriesEditEntryIdImport.update({
    path: '/reviews/$userId/entries/edit/$entryId',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/ama-sessions/$id': {
      id: '/ama-sessions/$id'
      path: '/ama-sessions/$id'
      fullPath: '/ama-sessions/$id'
      preLoaderRoute: typeof AmaSessionsIdImport
      parentRoute: typeof rootRoute
    }
    '/articles/$id': {
      id: '/articles/$id'
      path: '/articles/$id'
      fullPath: '/articles/$id'
      preLoaderRoute: typeof ArticlesIdImport
      parentRoute: typeof rootRoute
    }
    '/articles/create': {
      id: '/articles/create'
      path: '/articles/create'
      fullPath: '/articles/create'
      preLoaderRoute: typeof ArticlesCreateImport
      parentRoute: typeof rootRoute
    }
    '/articles/search': {
      id: '/articles/search'
      path: '/articles/search'
      fullPath: '/articles/search'
      preLoaderRoute: typeof ArticlesSearchImport
      parentRoute: typeof rootRoute
    }
    '/authors/$id': {
      id: '/authors/$id'
      path: '/authors/$id'
      fullPath: '/authors/$id'
      preLoaderRoute: typeof AuthorsIdImport
      parentRoute: typeof rootRoute
    }
    '/entries/$id': {
      id: '/entries/$id'
      path: '/entries/$id'
      fullPath: '/entries/$id'
      preLoaderRoute: typeof EntriesIdImport
      parentRoute: typeof rootRoute
    }
    '/users/$id': {
      id: '/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof UsersIdImport
      parentRoute: typeof rootRoute
    }
    '/users/search': {
      id: '/users/search'
      path: '/users/search'
      fullPath: '/users/search'
      preLoaderRoute: typeof UsersSearchImport
      parentRoute: typeof rootRoute
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchIndexImport
      parentRoute: typeof rootRoute
    }
    '/articles/edit/$id': {
      id: '/articles/edit/$id'
      path: '/articles/edit/$id'
      fullPath: '/articles/edit/$id'
      preLoaderRoute: typeof ArticlesEditIdImport
      parentRoute: typeof rootRoute
    }
    '/authors/edit/$id': {
      id: '/authors/edit/$id'
      path: '/authors/edit/$id'
      fullPath: '/authors/edit/$id'
      preLoaderRoute: typeof AuthorsEditIdImport
      parentRoute: typeof rootRoute
    }
    '/entries/create-review/$id': {
      id: '/entries/create-review/$id'
      path: '/entries/create-review/$id'
      fullPath: '/entries/create-review/$id'
      preLoaderRoute: typeof EntriesCreateReviewIdImport
      parentRoute: typeof rootRoute
    }
    '/users/edit/$id': {
      id: '/users/edit/$id'
      path: '/users/edit/$id'
      fullPath: '/users/edit/$id'
      preLoaderRoute: typeof UsersEditIdImport
      parentRoute: typeof rootRoute
    }
    '/authors/create/': {
      id: '/authors/create/'
      path: '/authors/create'
      fullPath: '/authors/create'
      preLoaderRoute: typeof AuthorsCreateIndexImport
      parentRoute: typeof rootRoute
    }
    '/entries/books/edit/$id': {
      id: '/entries/books/edit/$id'
      path: '/entries/books/edit/$id'
      fullPath: '/entries/books/edit/$id'
      preLoaderRoute: typeof EntriesBooksEditIdImport
      parentRoute: typeof rootRoute
    }
    '/entries/movies/edit/$id': {
      id: '/entries/movies/edit/$id'
      path: '/entries/movies/edit/$id'
      fullPath: '/entries/movies/edit/$id'
      preLoaderRoute: typeof EntriesMoviesEditIdImport
      parentRoute: typeof rootRoute
    }
    '/reviews/$userId/entries/$entryId': {
      id: '/reviews/$userId/entries/$entryId'
      path: '/reviews/$userId/entries/$entryId'
      fullPath: '/reviews/$userId/entries/$entryId'
      preLoaderRoute: typeof ReviewsUserIdEntriesEntryIdImport
      parentRoute: typeof rootRoute
    }
    '/entries/books/create/': {
      id: '/entries/books/create/'
      path: '/entries/books/create'
      fullPath: '/entries/books/create'
      preLoaderRoute: typeof EntriesBooksCreateIndexImport
      parentRoute: typeof rootRoute
    }
    '/entries/movies/create/': {
      id: '/entries/movies/create/'
      path: '/entries/movies/create'
      fullPath: '/entries/movies/create'
      preLoaderRoute: typeof EntriesMoviesCreateIndexImport
      parentRoute: typeof rootRoute
    }
    '/reviews/$userId/entries/edit/$entryId': {
      id: '/reviews/$userId/entries/edit/$entryId'
      path: '/reviews/$userId/entries/edit/$entryId'
      fullPath: '/reviews/$userId/entries/edit/$entryId'
      preLoaderRoute: typeof ReviewsUserIdEntriesEditEntryIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AmaSessionsIdRoute,
  ArticlesIdRoute,
  ArticlesCreateRoute,
  ArticlesSearchRoute,
  AuthorsIdRoute,
  EntriesIdRoute,
  UsersIdRoute,
  UsersSearchRoute,
  SearchIndexRoute,
  ArticlesEditIdRoute,
  AuthorsEditIdRoute,
  EntriesCreateReviewIdRoute,
  UsersEditIdRoute,
  AuthorsCreateIndexRoute,
  EntriesBooksEditIdRoute,
  EntriesMoviesEditIdRoute,
  ReviewsUserIdEntriesEntryIdRoute,
  EntriesBooksCreateIndexRoute,
  EntriesMoviesCreateIndexRoute,
  ReviewsUserIdEntriesEditEntryIdRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/ama-sessions/$id",
        "/articles/$id",
        "/articles/create",
        "/articles/search",
        "/authors/$id",
        "/entries/$id",
        "/users/$id",
        "/users/search",
        "/search/",
        "/articles/edit/$id",
        "/authors/edit/$id",
        "/entries/create-review/$id",
        "/users/edit/$id",
        "/authors/create/",
        "/entries/books/edit/$id",
        "/entries/movies/edit/$id",
        "/reviews/$userId/entries/$entryId",
        "/entries/books/create/",
        "/entries/movies/create/",
        "/reviews/$userId/entries/edit/$entryId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/ama-sessions/$id": {
      "filePath": "ama-sessions/$id.tsx"
    },
    "/articles/$id": {
      "filePath": "articles/$id.tsx"
    },
    "/articles/create": {
      "filePath": "articles/create.tsx"
    },
    "/articles/search": {
      "filePath": "articles/search.tsx"
    },
    "/authors/$id": {
      "filePath": "authors/$id.tsx"
    },
    "/entries/$id": {
      "filePath": "entries/$id.tsx"
    },
    "/users/$id": {
      "filePath": "users/$id.tsx"
    },
    "/users/search": {
      "filePath": "users/search.tsx"
    },
    "/search/": {
      "filePath": "search/index.tsx"
    },
    "/articles/edit/$id": {
      "filePath": "articles/edit/$id.tsx"
    },
    "/authors/edit/$id": {
      "filePath": "authors/edit/$id.tsx"
    },
    "/entries/create-review/$id": {
      "filePath": "entries/create-review/$id.tsx"
    },
    "/users/edit/$id": {
      "filePath": "users/edit/$id.tsx"
    },
    "/authors/create/": {
      "filePath": "authors/create/index.tsx"
    },
    "/entries/books/edit/$id": {
      "filePath": "entries/books/edit/$id.tsx"
    },
    "/entries/movies/edit/$id": {
      "filePath": "entries/movies/edit/$id.tsx"
    },
    "/reviews/$userId/entries/$entryId": {
      "filePath": "reviews/$userId/entries/$entryId.tsx"
    },
    "/entries/books/create/": {
      "filePath": "entries/books/create/index.tsx"
    },
    "/entries/movies/create/": {
      "filePath": "entries/movies/create/index.tsx"
    },
    "/reviews/$userId/entries/edit/$entryId": {
      "filePath": "reviews/$userId/entries/edit/$entryId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
