/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ActorsCreateIndexImport } from './routes/actors/create/index'
import { Route as ActorsComponentsAuthorFormImport } from './routes/actors/components/AuthorForm'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ActorsCreateIndexRoute = ActorsCreateIndexImport.update({
  path: '/actors/create/',
  getParentRoute: () => rootRoute,
} as any)

const ActorsComponentsAuthorFormRoute = ActorsComponentsAuthorFormImport.update(
  {
    path: '/actors/components/AuthorForm',
    getParentRoute: () => rootRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/actors/components/AuthorForm': {
      id: '/actors/components/AuthorForm'
      path: '/actors/components/AuthorForm'
      fullPath: '/actors/components/AuthorForm'
      preLoaderRoute: typeof ActorsComponentsAuthorFormImport
      parentRoute: typeof rootRoute
    }
    '/actors/create/': {
      id: '/actors/create/'
      path: '/actors/create'
      fullPath: '/actors/create'
      preLoaderRoute: typeof ActorsCreateIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  ActorsComponentsAuthorFormRoute,
  ActorsCreateIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/actors/components/AuthorForm",
        "/actors/create/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/actors/components/AuthorForm": {
      "filePath": "actors/components/AuthorForm.tsx"
    },
    "/actors/create/": {
      "filePath": "actors/create/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
